import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col `}
      >
        <div className="navbar">
          <ul><Link href="/">Home</Link></ul>
          <ul><Link href="/categories/mujer">Mujeres</Link></ul>
          <ul><Link href="/categories/hombre">Hombres</Link></ul>
          <ul><Link href="/categories/nene">Nenes</Link></ul>
          <ul><Link href="/user">User</Link></ul>
        </div>
        <div className="flex-grow">
          {children}
        </div>
        <footer>
          <p>All rights reserved</p>
          <p>follow us</p>
          <Link href="/"> Return Home</Link>
        </footer>
      </body>
    </html>
  );
}


